### ISSUE TITLE
Communication error between arbotix board and PC

### ISSUE THREAD

**Issue by MartinJensen37** [AalborgUniversity-ControlLabs/start-here#1]
I've downloaded all the drivers and required arbotix software and put it inside the sketchbook folder of the Arduino 1.0.6. I then select the port and board(Arbotix w/ RX shield), but for some reason the following error occurs when I run the ArbotixBlink: `avrdude: stk500_getsync(): not in sync: resp=0x00`.

**Comment by kdhansen** [comment]
The Arbotix was faulty, we just changed it out with a new.
